import enum


class BledyAkordyWzgledemSiebie(enum.Enum):
    SUBDOMINANTA_PO_DOMINANCIE = 0
    MOLL_SUBDOMINANTA_PO_DOMINANCIE = 1
    SUBDOMINANTA_PO_DOMINANCIE_SEPTYMOWEJ = 2
    MOLL_SUBDOMINANTA_PO_DOMINANCIE_SEPTYMOWEJ = 3
    NIE_TONIKA_NA_POCZATEK = 4
    NIE_MOLL_TONIKA_NA_POCZATEK = 5
    NIE_TONIKA_NA_KONIEC = 6
    NIE_MOLL_TONIKA_NA_KONIEC = 7